export const actionTypes = {
    FIREBASE_ONCE: 'FIREBASE_ONCE',
    FIREBASE_ON: 'FIREBASE_ON',
    DATALIST_SELECTED:'DATALIST_SELECTED',
    NAV_EXPANDED:'NAV_EXPANDED',
    AUTH_USER_LOGIN:'AUTH_USER_LOGIN',
    AUTH_USER_SIGNOUT:'AUTH_USER_SIGNOUT',
    DATA_FILTER:'DATA_FILTER',
    DATA_LIST_ADD:'DATA_LIST_ADD',

    ON_AUTH_STATE_CHANGED:'ON_AUTH_STATE_CHANGED'
  }